<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.pxczxn</groupId>
        <artifactId>pxczxn-api</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>pxczxn-admin-api</artifactId>
    <packaging>jar</packaging>
    <name>pxczxn Admin API</name>
    <description>后台管理接口层 - Admin控制器</description>

    <dependencies>
        <!-- 认证模块 -->
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-auth</artifactId>
        </dependency>
        <!-- 业务模块 -->
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-system</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-file</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-gen</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-message</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-pay</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-job</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- WebSocket基础设施 -->
        <dependency>
            <groupId>top.pxczxn</groupId>
            <artifactId>pxczxn-websocket</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
