SELECT CASE WHEN CHECK_CLAUSE LIKE '%SECURITY_LOGOUT%' AND CHECK_CLAUSE LIKE '%ACCOUNT_UNLOCK%' THEN 'PASS' ELSE 'FAIL' END AS result
FROM information_schema.CHECK_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'chk_account_enforcement_measure';
