SELECT CASE WHEN CHECK_CLAUSE LIKE '%LOGIN_BLOCK%' AND CHECK_CLAUSE LIKE '%ACCOUNT_DEACTIVATE%' AND CHECK_CLAUSE LIKE '%DATA_CLEANUP%' THEN 'PASS' ELSE 'FAIL' END AS result
FROM information_schema.CHECK_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'chk_account_enforcement_measure';
