"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { LoaderCircle, Send, RefreshCw } from "lucide-react";
import { UserTopbar } from "../components/prototype-ui";
import { communityApi, type TeamSubmission, type TeamSummary } from "../lib/community-api";

const statusLabel: Record<string, string> = { TEAM_PENDING: "团队审核中", TEAM_REVISION_REQUIRED: "团队要求修改", TEAM_REJECTED: "团队已拒绝", PLATFORM_PENDING: "平台审核中", PLATFORM_REVISION_REQUIRED: "平台要求修改", PLATFORM_REJECTED: "平台已拒绝", PUBLISHED: "已发布" };

export default function TeamSubmissionsPage() {
  const [submissions, setSubmissions] = useState<TeamSubmission[]>([]); const [teams, setTeams] = useState<TeamSummary[]>([]); const [sourceArticleId, setSourceArticleId] = useState(""); const [targetTeamId, setTargetTeamId] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const submissionIdempotencyKey = useRef<string | null>(null);
  const load = async () => { setLoading(true); setError(""); try { const [mine, directory] = await Promise.all([communityApi.myTeamSubmissions(), communityApi.teams()]); setSubmissions(mine); setTeams(directory); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法加载投稿记录"); } finally { setLoading(false); } };
  useEffect(() => { void Promise.all([communityApi.myTeamSubmissions(), communityApi.teams()]).then(([mine, directory]) => { setSubmissions(mine); setTeams(directory); }).catch((cause: unknown) => { setError(cause instanceof Error ? cause.message : "Unable to load submissions"); }).finally(() => { setLoading(false); }); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSubmitting(true); setError(""); setNotice(""); if (submissionIdempotencyKey.current === null) submissionIdempotencyKey.current = `team-submission-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`; try { await communityApi.createTeamSubmission({ sourceArticleId, targetTeamId, idempotencyKey: submissionIdempotencyKey.current }); setNotice("投稿已创建，当前版本已固定并进入团队审核。"); setSourceArticleId(""); submissionIdempotencyKey.current = null; await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "投稿失败"); } finally { setSubmitting(false); } }
  return <><UserTopbar title="团队投稿" /><main className="page-shell" style={{ paddingTop: 28, paddingBottom: 48 }}><header style={{ display: "flex", justifyContent: "space-between", gap: 16, alignItems: "start", marginBottom: 20 }}><div><h1 style={{ margin: 0 }}>外部投稿</h1><p className="secondary">投稿会固定当前文章版本；团队和平台审核通过后将创建独立的团队文章。</p></div><button className="icon-button" onClick={() => void load()} aria-label="刷新投稿记录" title="刷新"><RefreshCw size={17} /></button></header><section className="surface" style={{ padding: 20, marginBottom: 20 }}><h2 style={{ fontSize: 18, marginTop: 0 }}>新建投稿</h2><form onSubmit={submit} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12, alignItems: "end" }}><label>文章 ID<input value={sourceArticleId} onChange={(e) => setSourceArticleId(e.target.value.trim())} required inputMode="numeric" placeholder="要投稿的个人文章 ID" /></label><label>目标团队<select value={targetTeamId} onChange={(e) => setTargetTeamId(e.target.value)} required><option value="">选择团队</option>{teams.map((team) => <option key={team.teamId} value={team.teamId}>{team.name}</option>)}</select></label><button className="primary-button" disabled={submitting} type="submit">{submitting ? <LoaderCircle className="spin" size={16} /> : <Send size={16} />}提交投稿</button></form></section>{error && <p className="inline-feedback error" role="alert">{error}</p>}{notice && <p className="inline-feedback success" role="status">{notice}</p>}<section className="surface" style={{ overflowX: "auto" }}><div style={{ padding: "16px 20px 0" }}><h2 style={{ fontSize: 18, margin: 0 }}>我的投稿</h2></div>{loading ? <div className="text-center" style={{ padding: 56 }}><LoaderCircle className="spin" /></div> : submissions.length === 0 ? <p className="secondary" style={{ padding: 20 }}>还没有投稿记录。</p> : <table className="data-table"><thead><tr><th>文章</th><th>团队</th><th>状态</th><th>固定版本</th><th>反馈</th><th>发布时间</th></tr></thead><tbody>{submissions.map((item) => <tr key={item.id}><td>{item.sourceArticleTitle}<small className="muted">#{item.sourceArticleId}</small></td><td>{teams.find((team) => team.teamId === item.targetTeamId)?.name || item.targetTeamId}</td><td><span className="status-badge">{statusLabel[item.status] || item.status}</span></td><td>#{item.fixedSourceVersionId}</td><td>{item.platformReviewComment || item.teamReviewComment || "-"}</td><td>{item.publishedTeamArticleId ? "已生成团队文章" : "-"}</td></tr>)}</tbody></table>}</section></main></>;
}
