package top.pxczxn.community.abuse.application;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper; import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Propagation; import org.springframework.transaction.annotation.Transactional; import top.pxczxn.community.abuse.model.*; import top.pxczxn.community.abuse.persistence.*; import top.pxczxn.platform.common.exception.BusinessException; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.NoSuchAlgorithmException; import java.text.Normalizer; import java.time.*;
@Service @RequiredArgsConstructor public class CommunityAbuseGuard {
 private final CommunityAbuseWindowMapper windows; private final CommunityAbuseEventMapper events;
 @Transactional(propagation=Propagation.REQUIRES_NEW,noRollbackFor=BusinessException.class) public void check(String actorKey,String action,int threshold,int seconds){if(actorKey==null||actorKey.isBlank())throw new BusinessException(400,"Missing abuse actor");LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);CommunityAbuseWindow row=windows.selectOne(new QueryWrapper<CommunityAbuseWindow>().eq("actor_key",actorKey).eq("action_type",action).last("FOR UPDATE"));int attempts=1;if(row==null){row=new CommunityAbuseWindow();row.setActorKey(actorKey);row.setActionType(action);row.setWindowStartedAt(now);row.setAttemptCount(1);row.setRejectedCount(0);windows.insert(row);}else if(!row.getWindowStartedAt().plusSeconds(seconds).isAfter(now)){update(actorKey,action,now,1,row.getRejectedCount());}else{attempts=(row.getAttemptCount()==null?0:row.getAttemptCount())+1;update(actorKey,action,row.getWindowStartedAt(),attempts,attempts>threshold?(row.getRejectedCount()==null?1:row.getRejectedCount()+1):row.getRejectedCount());}boolean allowed=attempts<=threshold;CommunityAbuseEvent event=new CommunityAbuseEvent();event.setActorKey(actorKey);event.setActionType(action);event.setDecision(allowed?"ALLOW":"REJECT");event.setThreshold(threshold);event.setWindowSeconds(seconds);event.setAttemptCount(attempts);event.setOccurredAt(now);events.insert(event);if(!allowed)throw new BusinessException(429,"Too many "+action+" actions; retry after the policy window");}
 @Transactional(propagation=Propagation.REQUIRES_NEW,noRollbackFor=BusinessException.class) public void rejectDuplicateContent(Long userId,String scope,String content){if(userId==null||scope==null||scope.isBlank())throw new BusinessException(400,"Missing duplicate-content subject");String normalized=Normalizer.normalize(content==null?"":content,Normalizer.Form.NFKC).replaceAll("\\s+"," ").strip().toLowerCase(java.util.Locale.ROOT);if(normalized.isEmpty())return;check("CONTENT:"+userId+":"+sha256(normalized),scope+"_DUPLICATE",1,600);}
 private static String sha256(String value){try{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder result=new StringBuilder(64);for(byte valueByte:bytes){result.append(String.format("%02x",valueByte));}return result.toString();}catch(NoSuchAlgorithmException exception){throw new IllegalStateException("SHA-256 unavailable",exception);}}
 private void update(String actor,String action,LocalDateTime started,int attempts,Integer rejected){windows.update(null,new UpdateWrapper<CommunityAbuseWindow>().eq("actor_key",actor).eq("action_type",action).set("window_started_at",started).set("attempt_count",attempts).set("rejected_count",rejected));}
}
