"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { LoaderCircle, UserPlus, UserMinus } from "lucide-react";
import { UserTopbar } from "../../../components/prototype-ui";
import { communityApi, type ArticleCollaboration } from "../../../lib/community-api";

export function CollaborationArticlePanel({ articleId }: { articleId: string }) {
  const [rows, setRows] = useState<ArticleCollaboration[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [invitee, setInvitee] = useState(""); const [type, setType] = useState("CO_AUTHOR"); const [canEdit, setCanEdit] = useState(false); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setRows(await communityApi.collaborators(articleId)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "无法加载共创关系"); } finally { setLoading(false); } }, [articleId]);
  useEffect(() => { let active = true; void communityApi.collaborators(articleId).then((value) => { if (active) { setRows(value); setError(""); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "无法加载共创关系"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [articleId]);
  async function invite(event: FormEvent) { event.preventDefault(); setSaving(true); try { await communityApi.inviteCollaborator(articleId, { inviteeUserId: invitee, contributionType: type, canEdit, attributionOrder: rows.length + 1 }); setInvitee(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "邀请失败"); } finally { setSaving(false); } }
  async function revoke(row: ArticleCollaboration) { try { await communityApi.revokeCollaborator(articleId, row.id, row.lockVersion); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "撤销失败"); } }
  return <><UserTopbar title="文章共创" /><main className="page-shell" style={{ paddingTop: 28, paddingBottom: 44 }}><header style={{ marginBottom: 20 }}><h1 style={{ margin: 0 }}>文章共创</h1><p className="secondary">协作关系仅限当前文章。署名不自动授予编辑、发布、删除、审核或团队管理权限。</p></header>{error && <p role="alert" className="inline-feedback error">{error}</p>}<section className="surface" style={{ padding: 20, marginBottom: 18 }}><h2 style={{ fontSize: 18, marginTop: 0 }}>邀请协作者</h2><form onSubmit={invite} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12, alignItems: "end" }}><label>用户 ID<input required value={invitee} onChange={(event) => setInvitee(event.target.value.trim())} inputMode="numeric" /></label><label>贡献类型<select value={type} onChange={(event) => setType(event.target.value)}><option value="CO_AUTHOR">共同作者</option><option value="RESEARCH">研究</option><option value="REVIEW">审阅</option><option value="ILLUSTRATION">插画</option></select></label><label><input type="checkbox" checked={canEdit} onChange={(event) => setCanEdit(event.target.checked)} /> 允许编辑本文</label><button className="primary-button" disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <UserPlus size={16} />}发送邀请</button></form></section><section className="surface" style={{ padding: 20 }}><h2 style={{ fontSize: 18, marginTop: 0 }}>协作者与署名</h2>{loading ? <LoaderCircle className="spin" /> : rows.length === 0 ? <p className="secondary">暂时没有接受的协作者。</p> : <div>{rows.map((row) => <div key={row.id} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "12px 0", borderBottom: "1px solid var(--border-default)" }}><div><strong>{row.displayName || row.username || `用户 #${row.userId}`}</strong><span className="muted" style={{ marginLeft: 8 }}>#{row.attributionOrder} · {row.contributionType}{row.canEdit ? " · 可编辑" : " · 仅署名"}</span></div><button className="icon-button" type="button" title="移除协作者" aria-label="移除协作者" onClick={() => void revoke(row)}><UserMinus size={16} /></button></div>)}</div>}</section></main></>;
}
