// Core infrastructure
export { COMMUNITY_API_BASE_URL, CommunityApiError, communityRequest } from "./client";
export type { ApiResult } from "./client";
export { readSession, saveSession, SESSION_EVENT, NOTIFICATION_EVENT } from "./session";
export type { CommunitySession } from "./session";
export { publicFileUrl } from "./files";
export type { CommunityFile } from "./files";

// All domain types
export type {
  CurrentCommunityUser,
  BlogSettings,
  PersonalBlog,
  PublicBlog,
  ArticleAuthor,
  ArticleCategory,
  ArticleTag,
  PublicArticleSummary,
  PublicArticlePage,
  DiscoverySort,
  PublicDiscoveryPage,
  UnifiedSearchType,
  UnifiedSearchResult,
  UnifiedSearchPage,
  EditorialCollection,
  PublicArticleDetail,
  BlogCategory,
  PlatformTag,
  ArticleEditor,
  ArticleReviewTask,
  ArticleReviewStatus,
  CommunityContentType,
  ContentRelationship,
  LikeRelationship,
  FavoriteRelationship,
  FavoriteFolder,
  CommunityContentListItem,
  FavoriteContent,
  FavoriteContentPage,
  LikedContent,
  LikedContentPage,
  SocialCounts,
  BlogFollowRelationship,
  SocialProfile,
  SocialProfilePage,
  FollowingFeedItem,
  FollowingFeedPage,
  CreatorAnalytics,
  MomentAuthor,
  MomentBlog,
  MomentArticle,
  MomentSource,
  Moment,
  MomentPage,
  MomentFeedFilter,
  CommentAuthor,
  CommunityComment,
  CommentThread,
  CommentPage,
  NotificationCategory,
  CommunityNotification,
  NotificationPage,
  UnreadNotificationCount,
  TeamApplication,
  CommunityReport,
  CommunityBlock,
  CommunityAppeal,
  CommunitySanction,
  AppealContext,
  TeamInvitation,
  SubmittableArticle,
  TeamSummary,
  TeamSubmission,
  TeamPortalSettings,
  TeamMemberProfile,
  TeamPortal,
  TeamWorkspace,
  MyTeam,
  TeamStats,
  TeamTodo,
  TeamActivity,
  TeamArticleBrief,
  TeamDashboard,
  TeamMemberView,
  SeriesChapter,
  Series,
  SeriesReaderState,
  CommunityChatMessage,
  ArticleSeriesContext,
  ArticleCollaboration,
  SubmitTeamApplicationInput,
  AccountEnforcementCase,
  AccountEnforcementAppeal,
} from "./types";

// API client
export { communityApi } from "./api";