"use client";
import { Gavel, Loader2 } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { UserTopbar } from "../components/prototype-ui";
import { communityApi, type AppealContext, type CommunityAppeal } from "../lib/community-api";

export default function AppealsPage() {
  const [items, setItems] = useState<CommunityAppeal[]>([]); const [reportId, setReportId] = useState(""); const [context, setContext] = useState<AppealContext | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => communityApi.myAppeals().then(setItems).catch((error) => setMessage(error instanceof Error ? error.message : "加载失败"));
  useEffect(() => { let active = true; void communityApi.myAppeals().then((value) => { if (active) setItems(value); }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : "加载失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  async function inspect() { try { setMessage(""); setContext(await communityApi.appealContext(reportId)); } catch (error) { setContext(null); setMessage(error instanceof Error ? error.message : "无法读取处理决定"); } }
  async function submit(event: FormEvent) { event.preventDefault(); try { await communityApi.submitAppeal(reportId, { appealReason: reason }); setReason(""); setContext(null); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "提交失败"); } }
  return <><UserTopbar title="申诉中心" /><main className="page-shell stack" style={{ maxWidth: 960, paddingTop: 32 }}><header><h1 className="section-heading">申诉中心</h1><p className="secondary">仅被处理对象可查看原决定理由并申请复核。</p></header><section className="surface stack" style={{ padding: 20 }}><div style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: 12 }}><input className="field" value={reportId} onChange={(event) => setReportId(event.target.value)} placeholder="举报 ID" required /><button className="secondary-button" onClick={() => void inspect()} type="button">查看决定</button></div>{context && <div className="notice"><strong>{context.targetType} #{context.targetId}</strong><p>{context.resolutionCode || "已处理"} {context.resolutionNote || ""}</p></div>}<form className="stack" onSubmit={submit}><textarea className="field textarea" disabled={!context} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="说明申诉理由" required /><button className="primary-button" disabled={!context} type="submit"><Gavel size={16} />提交申诉</button></form>{message && <p role="alert" className="secondary">{message}</p>}</section><section className="surface stack" style={{ padding: 20 }}><h2 className="card-heading">我的申诉</h2>{loading ? <Loader2 className="animate-spin" /> : items.length === 0 ? <p className="secondary">暂无申诉记录。</p> : items.map((item) => <article className="list-row" key={item.id}><Gavel size={17} /><div style={{ flex: 1 }}><strong>举报 #{item.reportId}</strong><p className="secondary" style={{ margin: "2px 0 0" }}>{item.appealReason}</p></div><span className="chip">{item.status}</span></article>)}</section></main></>;
}
