<template>
  <div class="community-page">
    <header class="page-heading"><div><div class="page-eyebrow">TEAM GOVERNANCE</div><h1>团队治理</h1><p>查询团队状态、成员关系、审计记录与文章共创关系。</p></div><n-button :loading="loading" @click="load"><template #icon><n-icon><RefreshOutline /></n-icon></template>刷新</n-button></header>
    <n-tabs v-model:value="tab" type="line" @update:value="load"><n-tab name="teams">团队</n-tab><n-tab name="collaborations">共创关系</n-tab></n-tabs>
    <n-card><n-alert v-if="error" type="error" class="table-alert">{{ error }}</n-alert><n-data-table v-if="tab === 'teams'" :columns="teamColumns" :data="teams" :loading="loading" :row-key="(row: CommunityTeam) => row.id" :scroll-x="980" /><n-data-table v-else :columns="collaborationColumns" :data="collaborations" :loading="loading" :row-key="(row: CommunityCollaboration) => row.id" :scroll-x="1040" /><n-empty v-if="!loading && activeRows.length === 0" description="暂无记录" /></n-card>
    <n-modal v-model:show="showDetail" preset="card" title="团队详情" class="dialog-form-lg"><template v-if="detail"><n-descriptions :column="3" bordered size="small"><n-descriptions-item label="团队">{{ detail.name || '-' }}</n-descriptions-item><n-descriptions-item label="状态">{{ detail.status }}</n-descriptions-item><n-descriptions-item label="所有者">{{ detail.ownerUsername || detail.ownerUserId || '-' }}</n-descriptions-item></n-descriptions><n-divider>成员</n-divider><n-data-table :columns="memberColumns" :data="detail.members" :row-key="(row: CommunityTeamMember) => row.id" /><n-divider>最近审计记录</n-divider><n-data-table :columns="auditColumns" :data="detail.auditEvents" :row-key="(row: CommunityTeamAuditEvent) => row.id" /></template></n-modal>
  </div>
</template>
<script setup lang="ts">
import { computed, h, onMounted, ref } from 'vue'
import { RefreshOutline } from '@vicons/ionicons5'
import { NButton, NIcon, NTag } from 'naive-ui'
import { communityApi, type CommunityCollaboration, type CommunityTeam, type CommunityTeamAuditEvent, type CommunityTeamMember } from '@/api/community'
import { formatDateTime } from '@/utils/community'
const tab = ref<'teams' | 'collaborations'>('teams'); const loading = ref(false); const error = ref(''); const teams = ref<CommunityTeam[]>([]); const collaborations = ref<CommunityCollaboration[]>([]); const showDetail = ref(false); const detail = ref<CommunityTeam | null>(null)
const activeRows = computed(() => tab.value === 'teams' ? teams.value : collaborations.value)
const teamColumns = [{ title: '团队', key: 'name', minWidth: 180, render: (row: CommunityTeam) => h('div', [h('strong', row.name || `#${row.id}`), h('small', { class: 'muted' }, ` ${row.slug || ''}`)]) }, { title: '状态', key: 'status', width: 120, render: (row: CommunityTeam) => h(NTag, { size: 'small', type: row.status === 'ACTIVE' ? 'success' : 'warning' }, { default: () => row.status }) }, { title: '所有者', key: 'ownerUsername', width: 150, render: (row: CommunityTeam) => row.ownerUsername || row.ownerUserId || '-' }, { title: '成员', key: 'memberCount', width: 90 }, { title: '创建时间', key: 'createdAt', width: 170, render: (row: CommunityTeam) => formatDateTime(row.createdAt) }, { title: '操作', key: 'actions', width: 100, fixed: 'right' as const, render: (row: CommunityTeam) => h(NButton, { size: 'small', onClick: () => void open(row.id) }, { default: () => '详情' }) }]
const collaborationColumns = [{ title: '文章', key: 'articleTitle', minWidth: 220, render: (row: CommunityCollaboration) => h('div', [row.articleTitle || `#${row.articleId}`, h('small', { class: 'muted' }, ` #${row.articleId}`)]) }, { title: '协作者', key: 'username', width: 160, render: (row: CommunityCollaboration) => row.displayName || row.username || row.userId }, { title: '贡献', key: 'contributionType', width: 130 }, { title: '可编辑', key: 'canEdit', width: 90, render: (row: CommunityCollaboration) => row.canEdit ? '是' : '否' }, { title: '署名', key: 'attributionOrder', width: 80 }, { title: '状态', key: 'status', width: 100, render: (row: CommunityCollaboration) => h(NTag, { size: 'small', type: row.status === 'ACTIVE' ? 'success' : 'default' }, { default: () => row.status }) }, { title: '时间', key: 'createdAt', width: 170, render: (row: CommunityCollaboration) => formatDateTime(row.createdAt) }]
const memberColumns = [{ title: '成员', key: 'username', render: (row: CommunityTeamMember) => row.displayName || row.username || row.userId }, { title: '角色', key: 'roleCode' }, { title: '加入时间', key: 'joinedAt', render: (row: CommunityTeamMember) => formatDateTime(row.joinedAt) }]
const auditColumns = [{ title: '事件', key: 'eventType' }, { title: '目标', key: 'targetType', render: (row: CommunityTeamAuditEvent) => `${row.targetType || '-'} ${row.targetId || ''}` }, { title: '操作者', key: 'actorUserId', render: (row: CommunityTeamAuditEvent) => row.actorUserId || '-' }, { title: '时间', key: 'occurredAt', render: (row: CommunityTeamAuditEvent) => formatDateTime(row.occurredAt) }]
async function load() { loading.value = true; error.value = ''; try { if (tab.value === 'teams') teams.value = (await communityApi.teams({ pageNum: 1, pageSize: 50 })).list; else collaborations.value = (await communityApi.collaborations({ pageNum: 1, pageSize: 50 })).list } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : '加载失败' } finally { loading.value = false } }
async function open(id: string) { try { detail.value = await communityApi.team(id); showDetail.value = true } catch (cause: unknown) { error.value = cause instanceof Error ? cause.message : '加载详情失败' } }
onMounted(() => { void load() })
</script>
