<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.pxczxn</groupId>
        <artifactId>pxczxn-community</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>pxczxn-infra</artifactId>
    <packaging>pom</packaging>
    <name>pxczxn Infra</name>
    <description>基础设施层</description>

    <modules>
        <module>pxczxn-db</module>
        <module>pxczxn-redis</module>
        <module>pxczxn-oss</module>
        <module>pxczxn-websocket</module>
        <module>pxczxn-sms</module>
        <module>pxczxn-push</module>
        <module>pxczxn-pay</module>
        <module>pxczxn-wechat</module>
        <module>pxczxn-social</module>
        <module>pxczxn-crypto</module>
        <module>pxczxn-mail</module>
    </modules>
</project>
